### ISSUE TITLE
gRPC server address pattern is too strong

### ISSUE THREAD

**Issue by atcdot** [Forest33/warthog#1]
Hello!
Current gRPC server address pattern is `(([0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})|(\w*.\w*.\w*)):[0-9]{1,5}`
I have server with test stand address like `task-159-servicename.example.com:8080`. This is a valid address, but it is incompatible with the pattern.
The pattern should allow special characters and numbers.

**Comment by Forest33** [comment]
Hello!
Thanks, fixed.
