### ISSUE TITLE
"oidc" auth provider not supported for k8s port forwarding

### ISSUE THREAD

**Issue by urmaul** [Forest33/warthog#7]
I'm trying to use a server connection with K8s port forwarding but I see this error:

> code: 2
> message: no Auth Provider found for name "oidc"

I've checked my k8s config file and yes, it uses an auth provider with name `oidc`.

**Comment by Forest33** [comment]
Unfortunately, I don’t have the opportunity to check oidc right now, but you can check it in version 0.5.7

**Comment by urmaul** [comment]
Works great now. Thank you.
